In [36]:
import pandas as pd
import datetime as dt

from sqlalchemy import DateTime
import json


data = pd.read_csv("weatherdatasample.csv")

In [2]:
data

,Id,date,date_epoch,hour,maxtemp_c,maxtemp_f,mintemp_c,mintemp_f,avgtemp_c,avgtemp_f,...,condition_text,condition_icon,condition_code,uv,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,6,2025-02-25 00:00:00.0000000,1740355200,8,24.8,76.6,19.6,67.4,22.0,71.7,...,Sunny,//cdn.weatherapi.com/weather/64x64/day/113.png,1000,9,6,18,1,16,Waning Crescent,22
1,7,2025-02-25 00:00:00.0000000,1740441600,8,24.3,75.7,18.0,64.5,21.2,70.2,...,Sunny,//cdn.weatherapi.com/weather/64x64/day/113.png,1000,9,603,1856,233,1720,Waning Crescent,14
2,8,2025-02-27 12:24:47.2272840,1740614400,8,24.7,76.5,20.5,68.9,22.3,72.1,...,Partly cloudy,//cdn.weatherapi.com/weather/64x64/day/116.png,1003,9,604,1854,451,1835,Waning Crescent,3

In [32]:
len(list(data.iloc[ -1: , 1:]))

31

In [10]:
def connection_string():
    """this needs to be moved out

    Returns:
        string
    """
    return "mssql+pyodbc://@joshwork\\MSSQLSERVER02/db1?driver=ODBC+Driver+17+for+SQL+Server&Trusted_Connection=yes&TrustServerCertificate=yes"

In [33]:
input_example = data.iloc[ -1: , 1:]

In [34]:
input_example

,date,date_epoch,hour,maxtemp_c,maxtemp_f,mintemp_c,mintemp_f,avgtemp_c,avgtemp_f,maxwind_mph,...,condition_text,condition_icon,condition_code,uv,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
2,2025-02-27 12:24:47.2272840,1740614400,8,24.7,76.5,20.5,68.9,22.3,72.1,15.4,...,Partly cloudy,//cdn.weatherapi.com/weather/64x64/day/116.png,1003,9,604,1854,451,1835,Waning Crescent,3

datetime.datetime(2025, 4, 17, 17, 8, 23, 832332)

In [40]:
import random
newlist = [random.random()*100 for x in range(10)]

In [43]:
newlist

[61.269811376964256,
 89.60394255074543,
 93.58790172175094,
 26.113858679106418,
 83.26413890991459,
 36.365443218906016,
 26.105718339279417,
 63.25667429693599,
 65.03039335989085,
 0.7440461578726909]

In [42]:
random.randint()

TypeError: Random.randint() missing 2 required positional arguments: 'a' and 'b'

In [39]:
newlist

[False]

In [44]:
conditions = ["Raining", "Fire", "Cyclone", "Sunny", "Clowdy", "Partly Clowdy", "Stormy"]

In [45]:
moon_phase = ["Waning Crescent", "Full", "No Moon", "Partial Moon"]

In [50]:
import random

generated_df = []
for x in range(0, 1000):
    new_list = []
    new_list.append(dt.datetime.now() + dt.timedelta(days=x))
    new_list.append(1740614400)
    new_list.append(8)
    new_list.extend( [random.random()*100 for x in range(10)])
    new_list.extend( [random.randint(0, 50) for x in range(8)])
    new_list.append( conditions[random.randint(0,6)])
    new_list.append(f'//cdn.weatherapi.com/weather/64x64/day/{str(random.randint(100, 200))}.png')
    new_list.extend( [random.randint(0, 50) for x in range(6)])
    new_list.append(moon_phase[random.randint(0,2)])
    new_list.append(random.randint(0,20))
    generated_df.append(new_list)
    
df=pd.DataFrame(generated_df,columns=input_example.columns)
random.random()*100

44.76628291243433

In [51]:
df

,date,date_epoch,hour,maxtemp_c,maxtemp_f,mintemp_c,mintemp_f,avgtemp_c,avgtemp_f,maxwind_mph,...,condition_text,condition_icon,condition_code,uv,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,2025-04-17 17:25:08.106943,1740614400,8,76.732342,88.324913,34.356661,65.768759,22.848235,81.041835,29.330103,...,Sunny,//cdn.weatherapi.com/weather/64x64/day/196.png,22,32,38,19,26,43,No Moon,16
1,2025-04-18 17:25:08.107940,1740614400,8,39.104220,53.950455,9.093243,0.119056,22.643778,69.397987,0.092140,...,Clowdy,//cdn.weatherapi.com/weather/64x64/day/153.png,29,33,41,30,39,17,Waning Crescent,7
2,2025-04-19 17:25:08.107940,1740614400,8,29.221904,78.935289,17.070865,20.682120,13.511654,55.875677,81.490059,...,Fire,//cdn.weatherapi.com/weather/64x64/day/113.png,38,19,46,37,21,32,Waning Crescent,5
3,2025-04-20 17:25:08.107940,1740614400,8,1.029215,89.754454,66.935978,34.806731,87.356545,11.820011,56.072165,...,Stormy,//cdn.weatherapi.com/weather/64x64/day/132.png,1,18,48,32,34,37,No Moon,14
4,2025-04-21 17:25:08.107940,1740614400,8,85.578878,18.982437,51.651440,55.088989,0.090003,14.721285,75.408507,...,Sunny,//cdn.weatherapi.com/weather/64x64/day/197.png,10,9,11,42,7,27,Waning Crescent,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2028-01-07 17:25:08.133098,1740614400,8,83.576736,3.575564,19.867177,57.759394,23.124931,30.689070,85.660490,...,Stormy,//cdn.weatherapi.com/weather/64x64/day/182.png,46,37,37,15,28,29,Full,14
996,2028-01-08 17:25:08.133098,1740614400,8,52.834698,88.664138,30.262407,12.888453,49.379247,53.726061,72.304072,...,Fire,//cdn.weatherapi.com/weather/64x64/day/135.png,29,46,50,39,47,12,Full,14
997,2028-01-09 17:25:08.133098,1740614400,8,17.466307,19.202167,57.853232,38.629799,92.930853,64.920507,46.787421,...,Cyclone,//cdn.weatherapi.com/weather/64x64/day/137.png,48,47,11,50,7,40,No Moon,4
998,2028-01-10 17:25:08.133098,1740614400,8,86.878584,83.996898,64.928142,77.869214,35.993505,0.458894,69.018579,...,Clowdy,//cdn.weatherapi.com/weather/64x64/day/133.png,35,17,18,47,14,12,Full,18
999,2028-01-11 17:25:08.133098,1740614400,8,63.243702,8.975272,79.894504,76.176004,56.457030,45.657808,77.581919,...,Sunny,//cdn.weatherapi.com/weather/64x64/day/151.png,12,11,22,50,25,44,Waning Crescent,10

In [52]:
df.to_sql( 
        name="WeatherDataModels",
        con=connection_string(), 
        if_exists="append",
        index=False,
        dtype={'date' : DateTime()}
        )

62

In [48]:
new_list = []
new_list.append(dt.datetime.now() + dt.timedelta(days=0))
new_list.append(1740614400)
new_list.append(8)
new_list.extend( [random.random()*100 for x in range(10)])
new_list.extend( [random.randint(0, 50) for x in range(8)])
new_list.append( conditions[random.randint(0,6)])
new_list.append(f'//cdn.weatherapi.com/weather/64x64/day/{str(random.randint(100, 200))}.png')
new_list.extend( [random.randint(0, 50) for x in range(6)])
new_list.append(moon_phase[random.randint(0,2)])
new_list.append(random.randint(0,20))
new_list

[datetime.datetime(2025, 4, 17, 17, 22, 37, 428089),
 1740614400,
 8,
 60.552825743232354,
 63.96809103879421,
 45.82978192054581,
 59.196955013683336,
 19.098644802474197,
 64.86286197761792,
 17.02574353428995,
 37.49905979635327,
 26.123258246402447,
 27.140457194946922,
 7,
 25,
 29,
 35,
 17,
 43,
 46,
 33,
 'Sunny',
 '//cdn.weatherapi.com/weather/64x64/day/184.png',
 43,
 33,
 36,
 5,
 37,
 23,
 'Waning Crescent',
 18]

In [49]:
len(new_list)

31